Lecture(57, "PR", "Project Genetic Algorithms", [])
Lecture(58, "PR", "Project Numerical Recipes", [])
Lecture(59, "HC", "Reflectie op de digitale cultuur", [])
Lecture(60, "HC", "Reflectie op de digitale cultuur", [])
Lecture(61, "WC", "Reflectie op de digitale cultuur", [])
Lecture(62, "HC", "Software engineering", [])
Lecture(63, "WC", "Software engineering", [])
Lecture(64, "PR", "Software engineering", [])
Lecture(65, "HC", "Technology for games", [])
Lecture(66, "HC", "Technology for games", [])
Lecture(67, "WC", "Technology for games", [])
Lecture(68, "HC", "Webprogrammeren en databases", [])
Lecture(69, "HC", "Webprogrammeren en databases", [])
Lecture(70, "WC", "Webprogrammeren en databases", [])
Lecture(71, "PR", "Webprogrammeren en databases", [])
Lecture(72, "PR", "Zoeken, sturen en bewegen", [])
